#ifndef _BSP_H_
#define _BSP_H_


#include "ADC/ADC.h"
#include "delay/delay.h"
#include "GPIO/GPIO.h"
#include "PCA/PCA.h"
#include "EEPROM/stc15_eeprom.h"
#include "EXTI/stc15_exti.h"
#include "IIC/stc15_iic.h"
#include "PWM/stc15_pwm.h"
#include "SPI/stc15_spi.h"
#include "timer/timer.h"
#include "USART1/USART1.h"
#include <rtx51tny.h>                 /* RTX-51 tiny functions & defines      */
#endif
